Repository LGTM-Team/brain-game, pull requests merged in 2025-08, with the labels that each got.

#158 [fix] 다시하기 눌러도 게임 리셋이 안되는 버그 해결(#154)
  src/pages/Games/common/PlayPage.tsx
  src/pages/Games/common/styles/finishGame.module.css
  src/pages/Games/common/styles/playPage.module.css
  src/pages/Games/common/styles/startGame.module.css
Labels: fix

#179 [refactor] 콘솔로그 지우고 svg 에러 제거 (#null)
  src/pages/Games/common/PlayPage.tsx
  src/pages/Home/components/GameCard.tsx
Labels: refactor

#181 [fix] 회원가입 크로스 디바이스 구현 (#180)
  src/hooks/useSignUp.tsx
  src/pages/SignUp/PostSignUp.tsx
  src/pages/SignUp/SignUp.tsx
Labels: fix

#187 [fix] 랭킹 모달 게이지 버그 수정 (#186)
  src/common/modals/Ranking/RankingItem.tsx
Labels: fix

#196 [feat] 공유하기 기능구현 (#null)
  index.html
  package-lock.json
  package.json
  src/assets/icons/link.svg
  src/contexts/AuthContext.tsx
  src/main.tsx
  src/pages/Games/Share/ShareButton.tsx
  src/pages/Games/Share/SharePage.tsx
  src/pages/Games/Share/styles/shareButton.module.css
  src/pages/Games/Share/styles/sharePage.module.css
  src/pages/Games/common/GameResult.tsx
  src/pages/Games/common/PlayPage.tsx
  src/pages/Games/common/styles/gameResult.module.css
  src/pages/Games/gamePage.module.css
  src/pages/MyPage/MyPage.tsx
  src/pages/MyPage/components/getUserProfile.ts
  src/router/routes.tsx
  src/types/global.d.ts
Labels: feature

#202 [feat] 회원가입 벨리데이션 & 이메일 대기 페이지 배경 추가 (#199)
  src/common/form/Input.tsx
  src/common/styles/form.module.css
  src/pages/SignUp/components/styles/pendingEmail.module.css
  src/pages/SignUp/index.tsx
Labels: feature, ui

#205 [feat] 마이페이지 닉네임 수정 & 유저 정보 UI 수정 (#201)
  src/assets/icons/edit.svg
  src/hooks/useUpdateNickname.ts
  src/pages/MyPage/components/UserProfile.tsx
  src/pages/MyPage/components/userProfile.module.css
Labels: feature, ui, api

#215 [feat] 결과창에서 폭죽 효과 추가 (#214)
  package-lock.json
  package.json
  src/pages/Games/common/GameResult.tsx
  src/utils/confetti.ts
Labels: feature

#217 [ui] 배경 색상 변경, 쉐도우 효과 추가 (#216)
  src/styles/global.css
Labels: ui

#219 [feat] 이분 탐색 로직 추가 (#218)
  src/utils/isExistWord.ts
Labels: feature

#223 [feat] 계정찾기 라우팅 연결 (#222)
  src/common/form/Input.tsx
  src/hooks/usePasswordReset.ts
  src/pages/FindAccount/components/ResetPasswordPending.tsx
  src/pages/FindAccount/index.tsx
  src/pages/SignUp/components/styles/pendingEmail.module.css
  src/router/routes.tsx
Labels: feature, fix, ui, api

#226 [fix] 안드로이드 모바일 환경에서 게임중 input focus 유지 및 네비게이션바 렌더 토글 (#192)
  src/App.tsx
  src/contexts/KeyboardContext.tsx
  src/main.tsx
  src/pages/Games/common/SubmitAnswer.tsx
Labels: fix

#231 [docs] 발표전 리드미 수정 (#227)
  README.md
  src/assets/images/readme/readme_img.png
Labels: docs

#233 [docs] 리드미 정렬 문제 수정 (#null)
  README.md
Labels: docs

#234 [docs] 리드미 시연영상 누락 수정 (#null)
  README.md
Labels: docs
