Repository LGTM-Team/brain-game, pull requests merged in 2025-07, with the labels that each got.

#3 chore: <composite": true> ts 설정 추가
  tsconfig.app.json
Labels: chore

#26 feat: 회원가입 커스텀 훅 제작
  src/hooks/useSignUp.tsx
Labels: feature, api

#41 feat(auth): 비밀번호 재설정 커스텀 훅 제작 (#20)
  src/hooks/.gitkeep
  src/hooks/usePasswordReset.tsx
Labels: feature, api

#45 ui (input, submit): 공통 입력창, 버튼 창 추가(#8)
  src/components/Input.tsx
  src/components/SubmitButton.tsx
  src/components/styles/form.module.css
Labels: ui

#58 Feat/#44/sign up #44
  src/components/Input.tsx
  src/components/SubmitButton.tsx
  src/components/styles/form.module.css
  src/pages/SignUp/SignUp.module.css
  src/pages/SignUp/SignUp.tsx
  src/utils/.gitkeep
  src/utils/insertProfile.ts
Labels: feature, api

#74 [feat] 로그인 페이지 완성 (#69)
  src/components/form/Input.tsx
  src/components/styles/form.module.css
  src/pages/Login/Login.module.css
  src/pages/Login/Login.tsx
Labels: feature, ui, api

#77 [fix] 글로벌 css 수정 (#null)
  src/App.tsx
  src/components/styles/fixedLayout.module.css
  src/pages/Login/Login.module.css
  src/pages/SignUp/SignUp.module.css
  src/styles/global.css
Labels: fix

#80 [fix] 게임 공통 컴포넌트 레이아웃 깨짐 해결(#73)
  src/pages/Games/GamesPage.module.css
  src/pages/Games/components/GameResult.tsx
  src/pages/Games/components/styles/FinishGame.module.css
  src/pages/Games/components/styles/GameResult.module.css
  src/pages/Games/components/styles/StartCountdown.module.css
  src/pages/Games/components/styles/StartGame.module.css
Labels: fix

#81 [feat] 회원가입 이메일 인증 제거 (#75)
  src/pages/SignUp/SignUp.module.css
  src/pages/SignUp/SignUp.tsx
Labels: feature, ui

#85 [fix] PlayPage 공통 컴포넌트에 props 추가(#null)
  src/pages/Games/LetterColor/LetterColorPlay.tsx
  src/pages/Games/LetterColor/LetterColorPlayPage.tsx
  src/pages/Games/components/FinishGame.tsx
  src/pages/Games/components/GameResult.tsx
  src/pages/Games/components/PlayPage.tsx
  src/pages/Games/components/StartCountdown.tsx
Labels: fix

#88 [feat] 세션 여부에 따른 마이페이지 라우팅 분기 처리 (#87)
  src/components/layout/Navigation.tsx
  src/contexts/.gitkeep
  src/contexts/AuthContext.tsx
  src/main.tsx
  src/pages/MyPage/MyPage.tsx
  src/router/routes.tsx
Labels: feature, api

#93 [fear]글자 색 맞추기 게임(#86)
  src/assets/icons/submit.svg
  src/pages/Games/LetterColor/LetterColorPlay.module.css
  src/pages/Games/LetterColor/LetterColorPlay.tsx
  src/pages/Games/LetterColor/LetterColorPlayPage.tsx
  src/pages/Games/LetterColor/letterColorData.json
  src/pages/Games/components/PlayPage.tsx
  src/utils/getRandom.ts
Labels: feature

#96 [feat] 초성게임 완성 (#95)
  package-lock.json
  package.json
  src/data/wordList.json
  src/hooks/useBonusScore.tsx
  src/pages/Games/Chosung/Chosung.module.css
  src/pages/Games/Chosung/Chosung.tsx
  src/pages/Games/Chosung/ChosungPlayPage.tsx
  src/pages/Games/GamesPage.module.css
  src/pages/Games/GamesPage.tsx
  src/pages/Games/components/SubmitAnswer.tsx
  src/pages/Games/components/styles/SubmitAnswer.module.css
  src/router/routes.tsx
  src/utils/isExistWord.ts
  src/utils/makeRandomChosung.ts
Labels: feature, ui

#111 [feat] 다이나믹 타이머, 스태틱 타미어 구현 (#94)
  src/hooks/useBonusScore.tsx
  src/pages/Games/Choseong/Choseong.tsx
  src/pages/Games/Choseong/choseong.module.css
  src/pages/Games/Choseong/components/.gitkeep
  src/pages/Games/Choseong/index.tsx
  src/pages/Games/components/DynamicTimer.tsx
  src/pages/Games/components/StaticTimer.tsx
  src/pages/Games/components/styles/dynamicTimer.module.css
  src/pages/Games/components/styles/staticTimer.module.css
  src/router/routes.tsx
Labels: feature, fix

#116 [fix]글자색 맞추기 게임 윈도우 stroke(테두리) 에러 외 컴포넌트 적용(#106)
  src/pages/Games/LetterColor/components/LetterColorPlay.tsx
  src/pages/Games/LetterColor/components/letterColorPlay.module.css
  src/pages/Games/components/PlayPage.tsx
  src/pages/Games/components/SubmitAnswer.tsx
  src/pages/Games/components/styles/startGame.module.css
  src/pages/Games/components/styles/submitAnswer.module.css
Labels: fix

#122 [feat] 홈페이지 ui 제작
  src/assets/images/game/word_game.svg
  src/assets/images/home_img.svg
  src/pages/Home/HomePage.tsx
  src/pages/Home/components/GameCard.tsx
  src/pages/Home/components/styles/gameCard.module.css
  src/pages/Home/components/styles/style.module.css
  src/pages/Home/homePage.module.css
Labels: feature, ui

#124 [feat] 홈페이지 피드백 반영 (#null)
  src/components/layout/Header.tsx
  src/pages/Home/components/styles/gameCard.module.css
  src/pages/Home/components/styles/style.module.css
  src/styles/global.css
Labels: feature, ui

#127 [fix] 타이머 싱크 이슈 해결 (#126)
  src/pages/Games/components/DynamicTimer.tsx
  src/pages/Games/components/styles/dynamicTimer.module.css
  src/styles/global.css
Labels: fix

#128 [fix] 타이머 뉴로 박치기 이슈 재 수정 (#null)
  src/pages/Games/Choseong/choseong.module.css
  src/pages/Games/LetterColor/components/letterColorPlay.module.css
  src/styles/global.css
Labels: fix

#131 [refactor] 게임 튜토리얼 width 수정 (#null)
  src/pages/Games/components/styles/tutorial.module.css
Labels: refactor

#133 [feat] 계정 찾기 페이지 제작 (#83)
  src/assets/images/find-account.svg
  src/components/form/SubmitButton.tsx
  src/components/layout/navigationIcons.tsx
  src/components/styles/fixedLayout.module.css
  src/components/styles/form.module.css
  src/hooks/usePasswordReset.tsx
  src/pages/FindAccount/FindAccount.tsx
  src/pages/FindAccount/components/.gitkeep
  src/pages/FindAccount/findAccount.module.css
  src/pages/Home/components/GameCard.tsx
  src/pages/Login/Login.module.css
  src/pages/Login/Login.tsx
  src/pages/SignUp/SignUp.module.css
  src/pages/SignUp/SignUp.tsx
  src/router/routes.tsx
Labels: feature, fix, ui, api

#138 [feat] auth 관련 이메일 요청 로직 구현 (#137)
  src/assets/images/pending_img.svg
  src/hooks/useCurrentSession.tsx
  src/hooks/useLogin.tsx
  src/hooks/useSignUp.tsx
  src/pages/Login/Login.module.css
  src/pages/Login/Login.tsx
  src/pages/SignUp/PendingEmail.module.css
  src/pages/SignUp/PendingEmail.tsx
  src/pages/SignUp/PostSignUp.tsx
  src/pages/SignUp/SignUp.tsx
  src/router/routes.tsx
  src/utils/insertProfile.ts
Labels: feature, ui, api

#140 [feat]마이페이지 기능(#120)
  package-lock.json
  package.json
  src/assets/images/notice_neuro.svg
  src/pages/MyPage/MyPage.tsx
  src/pages/MyPage/components/MyRanking.tsx
  src/pages/MyPage/components/UserProfile.tsx
  src/pages/MyPage/components/getUserProfile.ts
  src/pages/MyPage/components/myRanking.module.css
  src/pages/MyPage/components/userProfile.module.css
  src/pages/MyPage/myPage.module.css
  src/pages/NotFound/NotFoundPage.tsx
  src/router/routes.tsx
Labels: feature
